In [1]:
import numpy as np
%load_ext tensorboard

In [3]:
x = np.array([[-2,-1],[3,4]])
y = np.array([[3,4],[1,2]])

In [4]:
x*y

array([[-6, -4],
       [ 3,  8]])

In [7]:
np.matmul(y,x)

array([[ 6, 13],
       [ 4,  7]])

In [8]:
np.matmul(x,y)

array([[ -7, -10],
       [ 13,  20]])

In [12]:
import tensorflow as tf

In [21]:
@tf.function
def simple_nn_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))
x = tf.constant([[-2,-1],[3,4]])
y = tf.constant([[3,4],[1,2]])
simple_nn_layer(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  0],
       [13, 20]], dtype=int32)>

In [3]:
%tensorboard --logdir logs --port 6006 --host 0.0.0.0 #Go to https://tb.jonai.teojy.com/


Reusing TensorBoard on port 6006 (pid 78), started 0:02:38 ago. (Use '!kill 78' to kill it.)